config/routes.rb
Rails.application.routes.draw do
  resources :production_trackings
  resources :employees
  resources :games
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  #get 'users/new'

  get 'static_pages/home'
  get 'static_pages/help'
  get  'static_pages/about'
  get  'static_pages/contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'users#index'
  root 'games#index'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]


end

app/models/game.rb
class Game < ApplicationRecord
	include Paperclip::Glue
	
	has_attached_file :photo, :styles => { 	:medium => "300x300>", 
											:large => "500x500>"},
	 :convert_options => {:thumb => "-gravity center -extent 100x100"},
	 :default_url => "/images/:style/missing.png",
	 :source_file_options =>  {:all => '-auto-orient'}#,
  	
  	validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  	validates_attachment_presence :photo
    validates_attachment_size :photo, :less_than => 5.megabytes

    has_one :production_tracking, dependent: :destroy
	has_many :employees

	STORES = ['App Store', 'Google Play', 'Windows Store']

	after_create :create_tracking

	private

		def create_tracking
			@production_tracking = ProductionTracking.create(game_id: self.id)
		end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :sort_users

  def index
    @games = Game.all
  end


  def show
  end


  def new
    @game = Game.new
  end


  def edit
  end


  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to games_path, notice: 'Game was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to games_path, notice: 'Game was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @game.destroy
    @game.photo = nil
    @game.save
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
    end
  end

  private

    def sort_users
      @games = Game.select {|g| g.production_tracking.nil? }
      @developers = Employee.where(type_of_work: "developer")
      @designers = Employee.where(type_of_work: "designer")
      @illustrators = Employee.where(type_of_work: "illustrator")
      @writers = Employee.where(type_of_work: "writer")
      @composers = Employee.where(type_of_work: "composer")
      @developers = Employee.where(type_of_work: "developer")
    end
   
    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:name, :package_name, :store, :production_tracking_id, :photo)
    end
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :package_name %>
    <%= f.text_field :package_name %>
  </div>

  <div class="field">
    <%= f.label :store %>
        <%= f.collection_select :store, Game::STORES, :to_s, :to_s, :include_blank => "choose a store"%>
  </div>

  <div>
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/games/_production_tracking_form.html.erb
<%= form_for(object) do |f| %>
<%= f.label :designer_id, class: "label label-default" %>
<%= f.collection_select(:designer_id, @designers.order(:name), :id, :name, {include_blank: "select a designer"}, {class: "form-control"}) %>

<%= f.label :illustrator_id, class: "label label-default" %>
<%= f.collection_select(:illustrator_id, @illustrators.order(:name),:id,:name, {include_blank: "select an illustrator"}, {class: "form-control"}) %>

<%= f.label :writer_id, class: "label label-default" %>
<%= f.collection_select(:writer_id, @writers.order(:name),:id,:name, {include_blank: "select a writer"}, {class: "form-control"}) %>

<%= f.label :composer_id, class: "label label-default" %>
<%= f.collection_select(:composer_id, @composers.order(:name),:id,:name, {include_blank: "selects a composer"}, {class: "form-control"}) %>

<%= f.label :developer_id, class: "label label-default" %>
<%= f.collection_select(:developer_id, @developers.order(:name),:id,:name, {include_blank: "select a developer"}, {class: "form-control"}) %>

<%= f.label :live%>
<%= f.check_box :live %>
<br>
  <div class="actions">
    <%= f.submit class: "btn btn-default"%>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games || <%= link_to 'New Game', new_game_path, class: "btn btn-info" %></h1>
<div class="container-fluid">
<table class="table table-hover">
  <% @games.each do |game| %>
    <div class="row-fluid-offset-0">
      <tr>
      <td>
        <%= image_tag game.photo.url(:medium)%>
      </td>
      <td>  
        title: <%= game.name %>
        <br>
        package: <%= game.package_name %>
        <br>
        store: <%= game.store %>
      </td>
      <td>
        <%if game.production_tracking %>
          designer: <%= game.production_tracking.designer.name if game.production_tracking.designer.present?%>
          <br>
          illustrator: <%= game.production_tracking.illustrator.name if game.production_tracking.illustrator.present?%>
          <br>
          writer: <%= game.production_tracking.writer.name if game.production_tracking.writer.present?%>
          <br>
          composer: <%= game.production_tracking.composer.name if game.production_tracking.composer.present?%>
          <br>
          developer: <%= game.production_tracking.developer.name if game.production_tracking.developer.present?%>  
          <br>
          <% if game.production_tracking.live %> 
            live: yes
          <% else %>
            live: no
          <% end %>
        <% end %>
      </td>
      <td>
        <% if game.production_tracking%>
          <%= render 'production_tracking_form', object: [game.production_tracking] %>
        <% else %>
          <%= render 'production_tracking_form', object: [game.build_production_tracking] %>
        <% end %>
      </td>
          <td>
          <div>
            <%= link_to 'Show', game, class: "btn btn-default" %>
          </div>
            <br>
          <div>
            <%= link_to 'Edit', edit_game_path(game), class: "btn btn-default" %>
          </div>  
            <br>
          <div>
            <%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
          </div>
          </td>
          </tr>
        </div>
      <% end %>
</table>
</div>
<br>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div class="container-fluid">

<table class="table">
<tr>
  <td>
    <%= image_tag @game.photo.url(:medium)%>
    <br>
	  <p>  
	    <%= link_to 'Show', @game %>
	    <%= link_to 'Edit', edit_game_path(@game) %>
	    <%= link_to 'Destroy', @game, method: :delete, data: { confirm: 'Are you sure?' } %>
	  </p>
  </td>
    
  <td><h4>
  	title: <%= @game.name %> || 
    package: <%= @game.package_name %> || 
    store: <%= @game.store %></h4>
  <p>
  <%if @game.production_tracking %>
    designer: <%= @game.production_tracking.designer.name if @game.production_tracking.designer.present? %>
    <br>
    illustrator: <%= @game.production_tracking.illustrator.name if @game.production_tracking.illustrator.present? %>
    <br>
    writer: <%= @game.production_tracking.writer.name if @game.production_tracking.writer.present? %>
    <br>
    composer: <%= @game.production_tracking.composer.name if @game.production_tracking.composer.present? %>
    <br>
    developer: <%= @game.production_tracking.developer.name if @game.production_tracking.developer.present? %>  
  <% end %>
  	<br> 
  	<% if @game.production_tracking.present? %>
  		status:<%= @game.production_tracking.live %>
  	<% else %>
  		not tracked
  	<% end %>
  </p>
  </td>
</tr>    
</table>
</div>