config/routes.rb
Rails.application.routes.draw do
  resources :production_trackings
  resources :employees
  resources :games
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  #get 'users/new'

  get 'static_pages/home'
  get 'static_pages/help'
  get  'static_pages/about'
  get  'static_pages/contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'users#index'
  root 'games#index'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]


end

app/models/production_tracking.rb
class ProductionTracking < ApplicationRecord
	belongs_to :designer, class_name: "Employee", optional: true
	belongs_to :writer, class_name: "Employee", optional: true
	belongs_to :composer, class_name: "Employee", optional: true
	belongs_to :illustrator, class_name: "Employee", optional: true
	belongs_to :developer, class_name: "Employee", optional: true
	belongs_to :game, optional: true

	after_update :change_employee_records, :remove_employees_from_track


	private

	def change_employee_records
		self.designer.update_column(:game_id, self.game_id) if self.designer
		self.illustrator.update_column(:game_id, self.game_id) if self.illustrator
		self.writer.update_column(:game_id, self.game_id) if self.writer
		self.composer.update_column(:game_id, self.game_id) if self.composer
		self.developer.update_column(:game_id, self.game_id) if self.developer
	end
	def remove_employees_from_track
		
		@design_trackings = ProductionTracking.where(designer_id: self.designer_id)
		@design_trackings.each {|t| t.update_column(:designer_id, nil) unless t == self}

		@illustration_trackings = ProductionTracking.where(illustrator_id: self.illustrator_id)
		@illustration_trackings.each {|t| t.update_column(:illustrator_id, nil) unless t == self}

		@write_trackings = ProductionTracking.where(writer_id: self.writer_id)
		@write_trackings.each {|t| t.update_column(:writer_id, nil) unless t == self}

		@compose_trackings = ProductionTracking.where(composer_id: self.composer_id)
		@compose_trackings.each {|t| t.update_column(:composer_id, nil) unless t == self}

		@developing_trackings = ProductionTracking.where(developer_id: self.developer_id)
		@developing_trackings.each {|t| t.update_column(:developer_id, nil) unless t == self}

	end


end

app/controllers/production_trackings_controller.rb
class ProductionTrackingsController < ApplicationController
  before_action :set_production_tracking, only: [:show, :edit, :update, :destroy]
  before_action :sort_users, only: [:new, :edit, :create, :update]

  def index
    @production_trackings = ProductionTracking.all
  end

  def show
  end


  def new
    @production_tracking = ProductionTracking.new
  end

  def edit
  end

  def create
    @production_tracking = ProductionTracking.new(production_tracking_params)

    respond_to do |format|
      if @production_tracking.save
        format.html { redirect_to :back, notice: 'Production tracking was successfully created.' }
        format.json { render :show, status: :created, location: @production_tracking }
      else
        format.html { render :new }
        format.json { render json: @production_tracking.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @production_tracking.update(production_tracking_params)
        format.html { redirect_to :back, notice: 'Production tracking was successfully updated.' }      
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @production_tracking.destroy
    respond_to do |format|
      format.html { redirect_to production_trackings_url, notice: 'Production tracking was successfully destroyed.' }
    end
  end

  private
    def sort_users
      @games = Game.select {|g| g.production_tracking.nil? }
      @designers = Employee.where(type_of_work: "designer")
      @illustrators = Employee.where(type_of_work: "illustrator")
      @writers = Employee.where(type_of_work: "writer")
      @composers = Employee.where(type_of_work: "composer")
      @developers = Employee.where(type_of_work: "developer")
    end
    def set_production_tracking
      @production_tracking = ProductionTracking.find(params[:id])
    end

    def production_tracking_params
      params.require(:production_tracking).permit(:game_id, :designer_id, :illustrator_id, :writer_id, :composer_id, :developer_id, :live)
    end
end

app/views/production_trackings/_form.html.erb
<%= form_for(production_tracking) do |f| %>
  <% if production_tracking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(production_tracking.errors.count, "error") %> prohibited this production_tracking from being saved:</h2>

      <ul>
      <% production_tracking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :game_id, class: "label label-default" %>
    <%= f.collection_select(:game_id, @games, :id, :name, {include_blank: "select a game"}, {class: "form-control"} )%>

    <%= f.label :designer_id, class: "label label-default" %>
    <%= f.collection_select(:designer_id, @designers.order(:name), :id, :name, {include_blank: "select a designer"}, {class: "form-control"}) %>

    <%= f.label :illustrator_id, class: "label label-default" %>
    <%= f.collection_select(:illustrator_id, @illustrators.order(:name),:id,:name, {include_blank: "select an illustrator"}, {class: "form-control"}) %>

    <%= f.label :writer_id, class: "label label-default" %>
    <%= f.collection_select(:writer_id, @writers.order(:name),:id,:name, {include_blank: "select a writer"}, {class: "form-control"}) %>

    <%= f.label :composer_id, class: "label label-default" %>
    <%= f.collection_select(:composer_id, @composers.order(:name),:id,:name, {include_blank: "selects a composer"}, {class: "form-control"}) %>

    <%= f.label :developer_id, class: "label label-default" %>
    <%= f.collection_select(:developer_id, @developers.order(:name),:id,:name, {include_blank: "select a developer"}, {class: "form-control"}) %>

  <br>
    <%= f.label :live%>
    <%= f.check_box :live %>
  <br>
  <br>

  <div class="actions">
    <%= f.submit class: "btn btn-default"%>
  </div>
<% end %>

app/views/production_trackings/edit.html.erb
<h1>Editing Production Tracking</h1>

<%= render 'form', production_tracking: @production_tracking %>

<%= link_to 'Show', @production_tracking %> |
<%= link_to 'Back', production_trackings_path %>

app/views/production_trackings/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'New Production Tracking', new_production_tracking_path, class: "btn btn-info" %>
<h1>Production Trackings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Game</th>
      <th>Designer</th>
      <th>Illustrator</th>
      <th>Writer</th>
      <th>Composer</th>
      <th>Developer</th>
      <th>Live</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @production_trackings.each do |production_tracking| %>
      <tr>
        <td><%= production_tracking.game.name if production_tracking.game %></td>
        <td><%= production_tracking.designer.name if production_tracking.designer %></td>
        <td><%= production_tracking.illustrator.name if production_tracking.illustrator %></td>
        <td><%= production_tracking.writer.name if production_tracking.writer %></td>
        <td><%= production_tracking.composer.name if production_tracking.composer %></td>
        <td><%= production_tracking.developer.name if production_tracking.developer %></td>
        <td>
        <div>
          <% if production_tracking.live %>
            yes
          <% else %>
            no
          <% end %>
        </div>
        <br>
        <div>
          <%= form_for(production_tracking) do |f| %>
              <td>
              <%= f.check_box :live  %>
              </td>
              <td>
              <%= f.submit "update status", class: "btn btn-large btn-default" %>
              </td>
          <% end %>
        </div>
        </td>
        <td><%= link_to 'Show', production_tracking %></td>
        <td><%= link_to 'Edit', edit_production_tracking_path(production_tracking) %></td>
        <td><%= link_to 'Destroy', production_tracking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/production_trackings/new.html.erb
<h1>New Production Tracking</h1>

<%= render 'form', production_tracking: @production_tracking %>

<%= link_to 'Back', production_trackings_path %>

app/views/production_trackings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @production_tracking.game.name if @production_tracking.game %>
</p>

<p>
  <strong>Designer:</strong>
  <%= @production_tracking.designer.name if @production_tracking.designer %>
</p>

<p>
  <strong>Illustrator:</strong>
  <%= @production_tracking.illustrator.name if @production_tracking.illustrator %>
</p>

<p>
  <strong>Writer:</strong>
  <%= @production_tracking.writer.name if @production_tracking.writer %>
</p>

<p>
  <strong>Composer:</strong>
  <%= @production_tracking.composer.name if @production_tracking.composer %>
</p>

<p>
  <strong>Developer:</strong>
  <%= @production_tracking.developer.name if @production_tracking.developer %>
</p>

<p>
  <strong>Live:</strong>
  <%= @production_tracking.live %>
</p>

<%= link_to 'Edit', edit_production_tracking_path(@production_tracking) %> |
<%= link_to 'Back', production_trackings_path %>